name: Build Plugin ZIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull latest fullcalendar
        run: |
          mkdir fullcalendar tmp && cd tmp
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/fullcalendar/fullcalendar/releases/latest | jq .assets[0].browser_download_url | xargs wget
          unzip fullcalendar-*.zip
          # Turn on extended globbing
          shopt -s extglob
          mv lib/*.min.* ../fullcalendar
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: rotaract-appointments
          path: |
            ./*
            !tmp
            !.*
